name: promobook
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.1+4

  google_maps_flutter: ^0.5.19+2
  location: ^2.3.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - lib/assets/starwars.jpg
    - lib/assets/starwars1.jpg
    - lib/assets/netflix.png
    - lib/assets/1.jpg
    - lib/assets/2.jpg
    - lib/assets/3.jpg
    - lib/assets/4.jpg
    - lib/assets/5.jpg
    - lib/assets/6.jpg
    - lib/assets/7.jpg
    - lib/assets/8.jpg
    - lib/assets/9.jpg
    - lib/assets/10.jpg
    - lib/assets/11.jpg
    - lib/assets/12.jpg
    - lib/assets/22.jpg
    - lib/assets/birdboxBanner.jpg

